FROM python:3.12-slim
WORKDIR /code
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
COPY ./uv.lock ./pyproject.toml ./README.md /code/
RUN uv sync --frozen
COPY ./ /code/
COPY ./docker/entrypoint.sh /usr/bin/entrypoint
RUN chmod +x /usr/bin/entrypoint
ENTRYPOINT [ "/usr/bin/entrypoint" ]